### PR TITLE
Upgrade to the newest verion of docx4j (6.1.0)

### PR DESCRIPTION
**Pull request by ImanGharib**
I upgraded to 6.1.0 version of docx4j. 
Resolves:
[#55](https://github.com/thombergs/docx-stamper/pull/55)

### CODE REVIEW

**Comment by ImanGharib** [comment]
Hi @joffrey-bion,
I have upgraded to 6.1.0
regards Iman

**Comment by KittyHawk03** [comment]
Hi, will this ever be merged into the main branch and updated on Maven Central?

**Comment by DDtKey** [comment]
Hi @thombergs,
Docx-stamper have a chance for further development?
Do pull request make sense?

**Comment by thombergs** [comment]
@DDtKey I'll have some time on my hands in September and go through all PRs then

**Comment by thombergs** [comment]
Thanks for the PR.

docx4j has now already been upgraded to 6.1.2, so I close this PR.

**Pull request closed without merging**
