### PR TITLE
Bug fix: different formatting in same paragraph

### PR DESCRIPTION
**Pull request by ImanGharib**
Each placeholder gets its own style from the run in wich it exists. 
related to [issue 67] (https://github.com/thombergs/docx-stamper/issues/67) [68](https://github.com/thombergs/docx-stamper/issues/68), [64] (https://github.com/thombergs/docx-stamper/issues/64)

### CODE REVIEW

**Comment by ImanGharib** [comment]
The placeholders won't lose the style anymore

**Comment by ImanGharib** [comment]
Hi @nor-deen,
thanks for your information. It happened if placeholders where in the same run. Would be great if you could check it too.

**Comment by nor-deen** [comment]
Thanks, I "fixed" it(?) with this ~hack~ change
PlaceholderReplacer.java:107 `rPr = collect.isEmpty()? null :collect.get(0);`

**Comment by ImanGharib** [comment]
has a bug in traversing the runs, which is to be fixed

**Pull request closed without merging**
