### PR TITLE
Fix for #13 (second try)

### PR DESCRIPTION
**Pull request by crivera**

### CODE REVIEW

**Comment by thombergs** [comment]
Made a few changes. Thanks for the contribution. 

Please make a separate branch for each PR the next time. If you work on "master" it makes it hard to distinguish from my own master which makes it complicated to work with a PR for me.

**Comment by thombergs** [comment]
Also, please don't change fundamental configuration like the supported java version or the version in pom.xml.

**Comment by thombergs** [comment]
new release with your feature is on it's way to maven central. Have fun :).

**Comment by crivera** [comment]
Awesome!!! Thanks! This was my first time contributing! Thanks a lot

**Pull request merged**
