### PR TITLE
Fixes CoordinatesWalker

### PR DESCRIPTION
**Pull request by asm0dey**
Now it can correctly handle rowContentElement if it is Tc (and thus can't be JAXBElement) itself

### CODE REVIEW

**Comment by thombergs** [comment]
I had to fix a compile error, see https://github.com/thombergs/docx-stamper/commit/18f6063313a434bcbc55952d93cbe7348d1a3819

I will configure an automatic build for each pull request, so you can see directly if there are any problems with compiling or unit tests.

**Comment by asm0dey** [comment]
Thank you very much and sorry for not running build before pull request.
Could you please release new version with this fix?

вс, 1 янв. 2017 г., 18:25 Tom Hombergs <notifications@github.com>:

**Comment by asm0dey** [comment]
Could you please release new version with fix?

**Comment by thombergs** [comment]
release 1.0.5 is on the way, should be accessible via Maven Central tomorrow

**Comment by asm0dey** [comment]
Thank you!

**Pull request merged**
